### ISSUE TITLE
interacting with file crashes the shell

### ISSUE THREAD

**Issue by Naadiyaar** [Rosettea/Hilbish#333] opened 2024-12-20 09:08 UTC
Trying to perform any action on this particular file fails with hilbish crashing.
Tried commands `ls` `mv` `ffprobe` and all of them forces shell to exit with code 2.
Also checked with another shell (bash) and everything is ok.

I'm using hilbish-git version `2.3.3.36ce05e` from Fedora Copr.

output I get:
```txt
=> mv Tradeoffs,\ Bad\ Science,\ and\ Polar\ Bears\ –\ The\ World\ of\ Java\ Optimisation\ \ By\ \ Holly\ Cummins\ \[PvZaDo_I21g\].mkv j.mkv
panic: regexp: Compile("^Tradeoffs, Bad Science, and Polar Bears \xe2\u0080\x93 The World of Java Optimisation  By  Holly Cummins [PvZaDo_I21g]\\.mkv$"): error parsing regexp: invalid UTF-8: `� The World of Java Optimisation  By  Holly Cummins [PvZaDo_I21g]\.mkv$`

goroutine 1 [running]:
regexp.MustCompile({0xc0002ba380, 0x73})
        /usr/local/go/src/regexp/regexp.go:313 +0xb4
mvdan.cc/sh/v3/expand.(*Config).glob(0xc0000a9040, {0xc000528120, 0x17}, {0xc00009acb0, 0x6f})
        /go/pkg/mod/github.com/!rosettea/sh/v3@v3.4.0-0.dev.0.20240815163633-562273e09b73/expand/expand.go:964 +0x2ee
mvdan.cc/sh/v3/expand.Fields(0x5e7438?, {0xc000013788, 0x3, 0x8dafc0?})
        /go/pkg/mod/github.com/!rosettea/sh/v3@v3.4.0-0.dev.0.20240815163633-562273e09b73/expand/expand.go:472 +0x2c5
mvdan.cc/sh/v3/interp.(*Runner).fields(0xc0000e0308, {0xc000013788?, 0xca8100?, 0x480000000000?})
        /go/pkg/mod/github.com/!rosettea/sh/v3@v3.4.0-0.dev.0.20240815163633-562273e09b73/interp/runner.go:197 +0x27
mvdan.cc/sh/v3/interp.(*Runner).cmd(0xc0000e0308, {0x9e29b8, 0xca8100}, {0x9e1348, 0xc0003a2820})
        /go/pkg/mod/github.com/!rosettea/sh/v3@v3.4.0-0.dev.0.20240815163633-562273e09b73/interp/runner.go:369 +0x13eb
mvdan.cc/sh/v3/interp.(*Runner).stmtSync(0xc0000e0308, {0x9e29b8, 0xca8100}, 0xc00034c7e0)
        /go/pkg/mod/github.com/!rosettea/sh/v3@v3.4.0-0.dev.0.20240815163633-562273e09b73/interp/runner.go:315 +0x26a
mvdan.cc/sh/v3/interp.(*Runner).stmt(0xc0000e0308, {0x9e29b8, 0xca8100}, 0xc00034c7e0)
        /go/pkg/mod/github.com/!rosettea/sh/v3@v3.4.0-0.dev.0.20240815163633-562273e09b73/interp/runner.go:296 +0x145
mvdan.cc/sh/v3/interp.(*Runner).Run(0xc0000e0308, {0x9e29b8, 0xca8100}, {0x9df748, 0xc00034c7e0})
        /go/pkg/mod/github.com/!rosettea/sh/v3@v3.4.0-0.dev.0.20240815163633-562273e09b73/interp/api.go:762 +0x14c
main.execCommand({0xc0000d17a0, 0x8b}, 0x0)
        /github/workspace/exec.go:320 +0x42f
main.execSh({0xc0000d17a0, 0x8b})
        /github/workspace/exec.go:253 +0x31
main.shRunner(0xc0000e8480, 0xc000041400)
        /github/workspace/runnermode.go:90 +0xb8
github.com/arnodel/golua/runtime.(*GoCont).RunInThread(0xc000041400, 0xc0000e8480)
        /go/pkg/mod/github.com/!rosettea/golua@v0.0.0-20241104031959-5551ea280f23/runtime/gocont.go:103 +0xe4
github.com/arnodel/golua/runtime.(*Thread).RunContinuation(0xc0000e8480, {0x9e4030?, 0xc000193420?})
        /go/pkg/mod/github.com/!rosettea/golua@v0.0.0-20241104031959-5551ea280f23/runtime/thread.go:98 +0x158
github.com/arnodel/golua/runtime.(*Thread).call(0xc0000e8480, {0x9de878?, 0xc00022ee40?}, {0xc000039960, 0x1, 0x7f881c2f3c58?}, {0x9e3fe8?, 0xc0003b8e40?})
        /go/pkg/mod/github.com/!rosettea/golua@v0.0.0-20241104031959-5551ea280f23/runtime/thread.go:276 +0xd3
github.com/arnodel/golua/runtime.Call(0xc0000d17a0?, {0x8b?, {0x91e9c0?, 0xc00022ee40?}}, {0xc000039960?, 0x8dae00?, 0xc0001c0000?}, {0x9e3fe8?, 0xc0003b8e40?})
        /go/pkg/mod/github.com/!rosettea/golua@v0.0.0-20241104031959-5551ea280f23/runtime/lib.go:144 +0x26e
main.runLuaRunner({0x1?, {0x91e9c0?, 0xc00022ee40?}}, {0xc0000d17a0, 0x8b})
        /github/workspace/exec.go:178 +0x1f0
main.handleSh({0xc0000d17a0, 0x8b})
        /github/workspace/exec.go:245 +0xd7
main.runInput({0xc0000d17a0, 0x8b}, 0x0)
        /github/workspace/exec.go:112 +0x385
main.main()
        /github/workspace/main.go:240 +0x12fd
```

**Comment by TorchedSammy** [comment] 2024-12-20 16:21
dupe of #183 

wrap it in quotes

**Closed** 2024-12-20 16:21 UTC
